---
repos:
  - repo: local
    hooks:
      - id: check-nix-fmt
        name: 'Check nix fmt'
        entry: 'nixpkgs-fmt'
        files: \.nix$
        language: system
        stages:
          - commit
          - push
