# CICD shell

## AD permissions

The permissions to target machines and perform actions are realized through our Active directory.
As an example to access the machines of the `middleware` hostgroup, you will need to be part of the `GP_APP_SALT_MIDDLEWARE` group.

Please fill in a `irisline` ticket to get the necessary permissions.

## Usage

### the `cicd` command line

The name of the command line utility is #cicd#. The first mandatory position argument is the zone (dev, testing, staging or prod). The general scheme of the command line looks like so:

```
cicd ZONE orch CMD                                 [-s STACK]
cicd ZONE runpuppet    [ROLE] [-n NODE] [-g GROUP] [-s STACK]
cicd ZONE facts        [ROLE] [-n NODE] [-g GROUP] [-s STACK] [-a --all]
cicd ZONE ping         [ROLE] [-n NODE] [-g GROUP] [-s STACK]
cicd ZONE runpuppet    [ROLE] [-n NODE] [-g GROUP] [-s STACK]
cicd ZONE data [-k KEY][ROLE] [-n NODE] [-g GROUP] [-s STACK]
cicd ZONE console
```

Here is the help as display on the command line:

```
→ cicd
CICD command line utility

Usage: cicd ZONE (console | stats | data | orch | facts | ping | du | runpuppet
            | sync | result)

Available options:
  -h,--help                Show this help text
  ZONE                     ZONE such as dev, staging, testing or prod

Available commands:
  console                  Open the specialized salt console
  stats                    Stats (special permission required)
  data                     Return configuration data for a specific property
  orch                     Run an orchestration command on the infrastructure
  facts                    Return essential facts about nodes
  ping                     Ping nodes
  du                       Return disk usage
  runpuppet                Apply puppet configuration
  sync                     Sync data from master to nodes
  result                   Display the results of the most recent jobs executed by the user or for a specific id
```

You can request the help at other level too. For instance:
```
→ cicd staging facts -h
```

[NOTE]
====
- These commands are executed remotely (if you have the right to execute them) through an API. Behind the scene they might call either the `puppetdb` or the `saltmaster`. For instance `cicd ZONE node facts NODE` would call the puppetdb and return a result even if the node is down.
- All commands to the saltmaster together with their results are recorded in a centralize database included the date and name of the person that execute them.
- By default, all commands target a specific default hostgroup/stack. You can look at the `devbox` README to know how to set the default value for your stack in the devbox.
====

### `data`

```
- docker version of your jenkins slave
```
→ cicd prod data jenkins.slave -k docker::version
{
  "fqdn": "svappcavl736.cirb.lan",
  "subgroup": "jenkins",
  "role": "slave",
  "docker::version": "1.9.1-25.el7"
}
```
→ cicd prod data -n svappcavl771.prd.srv.cirb.lan

### `facts`

You can toggle the `facts` query to target all hostgroups/stacks with the `-a/ --all` flag.

- Selection of interesting facts about all the jenkins slave in production:
```
λ ~ → cicd prod facts jenkins.slave -a
{
  "fqdn": "SVAPPCAVL595.cirb.lan",
  "ip": "192.168.34.153",
  "os": "CentOS 6.6",
  "subgroup": "jenkins",
  "role": "slave"
}
{
  "fqdn": "SVAPPCAVL649.prd.srv.cirb.lan",
  "ip": "192.168.34.9",
  "os": "RedHat 6.7",
  "subgroup": "jenkins",
  "role": "slave"
}
...


→ cicd prod facts -n svappcavl771.prd.srv.cirb.lan

### `run puppet`

```
→ cicd prod runpuppet jenkins.slave
→ cicd staging runpuppet -n svappcavl703.sta.srv.cirb.lan
```

### `du` (disk usage)

```
→ cicd staging du -n svappcavl703.sta.srv.cirb.lan
```

### `result`

You can view the result of any command by `jid` or request a display of the last `n` commands :
```
→ cicd testing result -j 20160621104434055991
→ cicd testing result -n 2
```

### `console`

.Open a #console in staging#
```
→ cicd staging console
```

One great feature of this specialized shell is the *automatic completion* (while typing) of the available nodes, commands, ... It acts as an interactive help to ease the task at hand.

#### examples

- Run puppet via the `pep` alias on two nodes:
```
pep -L foreman.sandbox.srv.cirb.lan,puppetdb.sandbox.srv.cirb.lan --client=local_async puppetutils.run_agent
```

### *Orchestration*

Salt can run multiple commands as well using the orchestrate runner. The orchestration is executed on the salt master to allow inter minion requisites, like ordering the application of states on different minions that must not happen simultaneously, or for halting the state run on all minions if a minion fails one of its states (more about this topic can be found https://docs.saltstack.com/en/latest/topics/tutorials/states_pt5.html#orchestrate-runner[in the saltstack website]).

The orchestration should be defined in the orch folder. You will find some examples http://stash.cirb.lan/projects/MIDDLEWARE/repos/salt-stack-middleware/browse/orch?at=refs%2Fheads%2Fmiddleware[here].

Orchestrate commands can be started using:

```
→ cicd testing orch CMD
```

## Install outside the devbox

To install the shell outside the devbox, the requirements are:

* OS: linux
* git
* nix

If you haven't installed `nix` already, here is the quick how to:

```
bash <(curl https://nixos.org/nix/install)
```
This will perform a single-user installation of Nix, meaning that /nix is owned by the invoking user. The script will only invoke `sudo` to create /nix if it doesn’t already exist. At that point, the script will prompt you for a password.

To activate `nix` in your shell, add the following line in your `.bash_profile`:

```
source ~/.nix-profile/etc/profile.d/nix.sh'
```

You will also need to fetch the `nixpkgs` source for https://github.com/CIRB/devbox/blob/master/user/config.nix including the `pkgs` folder.


## TODO

- [ ] update zsh completion
- [ ] in devbox, update `language-puppet`
- [ ] fix result -j (that works for run-puppet only)
- [ ] re-use cicd in the console (cicd prod stack ping -> stack ping)
- [ ] in devbox, insert this README
- [ ] use puppetdb instead of salt for stack_data_for
