# CICD shell


## Setup

To use the tool, you need to fill in the https://github.com/CIRB/devbox/blob/master/user/config/shell[configuration file] located in `/vagrant/config/shell`.

ifndef::env-devbox[]
It is installed as part of the devbox. Please read the section __Install_outside_the_devbox__ if you need to install it on a different system.
endif::env-devbox[]

## Usage

The name of the command line utility is #cicd#. The first mandatory position argument is the zone (dev, testing, staging or prod). The general scheme of the command line is:

```
cicd ZONE facts        [ROLE] [-n NODE] [-g GROUP] [-s STACK] [-a --all]
cicd ZONE runpuppet    [ROLE] [-n NODE] [-g GROUP] [-s STACK]
cicd ZONE ping         [ROLE] [-n NODE] [-g GROUP] [-s STACK]
cicd ZONE runpuppet    [ROLE] [-n NODE] [-g GROUP] [-s STACK]
cicd ZONE data [-k KEY][ROLE] [-n NODE] [-g GROUP] [-s STACK]
cicd ZONE orch CMD                                 [-s STACK]
cicd ZONE console
```

Here is the help as display by invoking #cicd# alone:

....
→ cicd
CICD command line utility (v1.1.0)

Usage: cicd ZONE (console | stats | data | orch | facts | ping | du | runpuppet
            | sync | result)

Available options:
  -h,--help                Show this help text
  ZONE                     ZONE such as dev, staging, testing or prod

Available commands:
  console                  Open the specialized salt console
  stats                    Stats (special permission required)
  data                     Return configuration data for a specific property
  orch                     Run an orchestration command on the infrastructure
  facts                    Return essential facts about nodes
  ping                     Ping nodes
  du                       Return disk usage
  service                  Service management for a specific node
  runpuppet                Apply puppet configuration
  sync                     Sync data from master to nodes
  result                   Display the results of jobs executed by the user
  gentags                  Generate node completion file
....

You can request the help at each level. For instance:
```
→ cicd staging facts -h
```

[NOTE]
====
- Commands are executed remotely through an API. Behind the scene they call either the `puppetdb`, the `saltmaster` or the `pgserver`.
- Commands to the saltmaster together with their results are recorded in a centralized database included the date and name of the person that executes them.
- By default, all commands target a specific default hostgroup/stack defined in `/vagrant/conf/shell`
====


### facts command

The command displays a subset of important facts (static information) about your nodes such as the `fqdn`, `ip`, `os`, `role`, ...

You can toggle the `facts` query to target all hostgroups/stacks with the `-a/ --all` flag. Here is how to get all facts for all slaves in every stack:

```
λ ~ → cicd prod facts jenkins.slave --all
{
  "fqdn": "SVAPPCAVL595.cirb.lan",
  "ip": "192.168.34.153",
  "os": "CentOS 6.6",
  "hostgroup": "irisbox",
  "subgroup": "jenkins",
  "role": "slave"
}
{
  "fqdn": "SVAPPCAVL649.prd.srv.cirb.lan",
  "ip": "192.168.34.9",
  "os": "RedHat 6.7",
  "hostgroup": "iam",
  "subgroup": "jenkins",
  "role": "slave"
}
...
```
As usual, use `-n` to target a single node:
```
→ cicd prod facts -n svappcavl771.prd.srv.cirb.lan
{
  "hostgroup": "fmx",
  "subgroup": "jenkins",
  "role": "slave",
  "os": "RedHat 7.2",
  "ip": "192.168.34.81",
  "puppet run": "Wed Dec  7 15:23:00 CET 2016",
  "jenkins job": "22"
}
```

TIP:  Use the `--down` flag  to gather `facts` on disconnected minions.


### data command

The command displays configuration data about your node. For instance you might display the docker version of your jenkins slave:

```
→ cicd prod data jenkins.slave -k docker::version
{
  "fqdn": "svappcavl736.cirb.lan",
  "subgroup": "jenkins",
  "role": "slave",
  "docker::version": "1.9.1-25.el7"
}
```

To display all known configuration of a specific node:
```
→ cicd prod data -n svappcavl771.prd.srv.cirb.lan
```

### run puppet command

The command runs the puppet agent on one or multiple nodes. For instance you can run the agent on all the dev nodes of your stack with:

```
→ cicd dev runpuppet
```

Or you can select a subgroup with

```
→ cicd dev runpuppet -g jenkins
```

### du command

The command displays disk usage. Try:
```
→ cicd staging du -n svappcavl703.sta.srv.cirb.lan
```

### result command

You can view the result of a `runpuppet` by using the provided job id (`jid`)
```
→ cicd testing result -j 20160621104434055991
```
In case the result is not yet available the command will automatically be retry 12 times (3 min).

You can also ask for the last n executed commands:
```
→ cicd testing result -n 2
```

### console command

For longer session within a specific zone, you can save some typing by opening a `console` for that zone. Inside the console, you would omit the zone from the command line. Here is an example:

```
→ cicd staging console

[cicd prod]$ facts
```

Another usage of the console is to run specific `salt` commands that are not exposed by the `cicd` command line. This is done via the #pep# shortcut. For instance:

```
[cicd prod] $ pep -L foreman.sandbox.srv.cirb.lan,puppetdb.sandbox.srv.cirb.lan --client=local_async puppetutils.run_agent
```

### orchestration command

Salt can run multiple commands as well using the orchestrate runner. The orchestration is executed on the salt master to allow inter minion requisites, like ordering the application of states on different minions that must not happen simultaneously, or for halting the state run on all minions if a minion fails one of its states (more about this topic can be found https://docs.saltstack.com/en/latest/topics/tutorials/states_pt5.html#orchestrate-runner[in the saltstack website]).

The orchestration should be defined in the orch folder. You will find some examples http://stash.cirb.lan/projects/MIDDLEWARE/repos/salt-stack-middleware/browse/orch?at=refs%2Fheads%2Fmiddleware[here].

Orchestrate commands can be started using:

```
→ cicd testing orch CMD
```

## Identification & authorization
====
The permissions to target machines and perform actions are realized through our Active directory.
As an example to access the machines of the `middleware` hostgroup, you will need to be part of the `GP_APP_SALT_MIDDLEWARE` group.

These permissions should have been set for you already. If they don't, please contact the `cicd` team.
====

ifndef::env-devbox[]

## Install outside the devbox

Before installing the `cicd-shell` on any linux systemfootnote:[`macos` might also work], you will need:

. the https://nixos.org/nix/[nix package manager] installed and active for your user.
. the https://github.com/CIRB/nixpkgs-config[cirb nixpkgs config]

You can then proceed to install with:

```
nix-env -f ~/.config/nixpkgs/pin.nix -i cicd-shell <1>
```
<1> the `-f` flag ensures that we point to the same nixpkgs version but can be omitted

====
If you haven't installed `nix` already, here is the quick how to:

```
bash <(curl https://nixos.org/nix/install)
```
This will perform a single-user installation of Nix, meaning that /nix is owned by the invoking user. The script will only invoke `sudo` to create /nix if it doesn’t already exist. At that point, the script will prompt you for a password.

To activate `nix` in your shell, add the following line in your `.bash_profile`:

```
source ~/.nix-profile/etc/profile.d/nix.sh'
```
====

endif::env-devbox[]
