resolver: lts-7.15
extra-deps:
- turtle-1.3.0
- optparse-applicative-0.13.0.0
packages:
- .
- location:
    git: https://github.com/sdiehl/protolude.git
    commit: fb6a942954ff0958350782b0cbd04f783c58f22f
