# CICD shell
ifndef::site-gen-antora[]
:toc:
ifdef::backend-html5,backend-docbook5[]
:toc-title:
endif::[]
:source-highlighter: highlightjs
:icons: font
endif::[]
:language: bash
:autofit-option:
## Setup

To use the `cicd shell`, you need to fill in the https://github.com/CIRB/devbox/blob/master/user/config/shell[configuration file] located in `/vagrant/config/shell`.

The shell is installed with the devbox. Please read the section <<_install_outside_the_devbox, Install outside the devbox>> if you need to install it on a different system.

It is also possible to run the shell within Docker. On linux for instance, you can do:

.~/projects/bric/cicd/shell
```
make run-docker CMD='dev facts --refresh'
#  or
./docker/run.sh dev facts --refresh
```

## Usage

The name of the command line utility is #cicd#. The first mandatory position argument is the zone (dev, testing, staging or prod).

.General scheme of the command line
[%autofit]
```
cicd ZONE facts                  [ROLE] [-n NODE] [-g GROUP] [-s STACK] [--all] [--down]
cicd ZONE runpuppet              [ROLE] [-n NODE] [-g GROUP] [-s STACK]
cicd ZONE service ACTION SERVICE [ROLE] [-n NODE] [-g GROUP] [-s STACK]
cicd ZONE orch    CMD                                        [-s STACK]
cicd ZONE result [-j JID] [-n NUM] [--raw]
cicd ZONE console

cicd doc (html | modules | mod MOD)
```

The auto-completion feature helps you to complete the command. You can also request the help at each level:

.General help output for #cicd#
....
→ cicd
CICD - command line utility (v2.0.6)

Usage: cicd (pass | doc | ZONE (console | stats | orch | facts | ping |
            du | state | service | foreman | runpuppet | sync | setfacts |
            result | gentags | validate))

Available options:
  -h,--help                Show this help text
  ZONE                     ZONE (dev|testing|staging|prod)

Available commands:
  pass                     Change password
  doc                      Documentation utilities
  console                  Open the cicd console
  stats                    Stats (special permission required)
  orch                     Run an orchestration command on the infrastructure
  facts                    Return essential facts about nodes
  ping                     Ping nodes
  du                       Return disk usage
  state                    Apply a specific configuration
  service                  Service management for a specific node
  foreman                  Display the foreman report in a browser
  runpuppet                Apply puppet configuration
  sync                     Sync metavar  data from master to nodes
  setfacts                 Set/update the 4 base machine facts
  result                   Results of the most user recent jobs or for a specific id
  gentags                  Generate node completion file
  validate                 Validate node with inspec
....

.Help output for #facts#
```
→ cicd staging facts -h
Usage: cicd facts [--refresh] [--down] [--all] [ROLE] [-n NODE] [-g GROUP]
                  [-s STACK] [--raw] [--quiet] [--dry]
  Return essential facts about nodes

Available options:
  --refresh                Refresh the cache
  --down                   Query disconnected node
  --all                    Target whole the known stacks
  ROLE                     Role name maybe prefixed by a subgroup ('subgroup.role')
  -n NODE                  Target node
  -g GROUP                 Target subgroup
  -s STACK                 Target stack/hostgroup
  --raw                    Raw output (no jq)
  --quiet                  Quieter output. Won't display the command.
  --dry                    Display the command without execution
  -h,--help                Show this help text
```

[NOTE]
====
- Commands are executed remotely through an API. Behind the scene they call either the `puppetdb`, the `saltmaster` or the `pgserver`.
- Commands to the saltmaster together with their results are recorded in a centralized database included the date and name of the person that executes them.
- By default, all commands target a specific default hostgroup/stack defined in `/vagrant/conf/shell`
====


### >_ facts

The command displays a subset of important facts (static information) about your nodes such as the `fqdn`, `ip`, `os`, `role`, ...

The facts are mostly static information. By default they are cached to give immediate feedback. To update the cache, use the `--refresh` flag.

You can toggle the `facts` query to target all hostgroups/stacks with the `--all` flag. Here is how to get all facts for all slaves in every stack:

```
λ ~ → cicd prod facts jenkins.slave --all
{
  "fqdn": "svappcavl736.prd.srv.cirb.lan",
  "ip": "192.168.34.52",
  "os": "RedHat 7.3",
  "hostgroup": "ci",
  "subgroup": "jenkins",
  "role": "slave",
  "instance": "middleware",
  "puppet run": "Mon Apr 16 11:33:41 CEST 2018",
  "jenkins job": "186"
}
{
  "fqdn": "svappcavl771.prd.srv.cirb.lan",
  "ip": "192.168.34.81",
  "os": "RedHat 7.4",
  "hostgroup": "ci",
  "subgroup": "jenkins",
  "role": "slave",
  "instance": "fmx",
  "puppet run": "Mon Apr 16 14:24:05 CEST 2018",
  "jenkins job": "188"
}
...
```
As usual, use `-n` to target a single node:
```
→ cicd prod facts -n svappcavl771.prd.srv.cirb.lan
{
  "fqdn": "svappcavl771.prd.srv.cirb.lan",
  "ip": "192.168.34.81",
  "os": "RedHat 7.4",
  "hostgroup": "ci",
  "subgroup": "jenkins",
  "role": "slave",
  "instance": "fmx",
  "puppet run": "Mon Apr 16 14:24:05 CEST 2018",
  "jenkins job": "188"
}
```

TIP:  Use the `--down` flag  to gather `facts` on a disconnected minion.


### >_ runpuppet

The command runs the puppet agent on one or multiple nodes. When a node is specified with `-n`, the command will wait back for a result.

```
→ cicd dev runpuppet -n svappcavl000.dev.srv.cirb.lan
```

On all other cases, the command first asks for confirmation, then returns quickly with a `jobid`.
The process is asynchronous because it might take quite a while to complete.

Here are some examples:

```
→ cicd dev runpuppet <1>
→ cicd dev runpuppet -g jenkins <2>
→ cicd dev runpuppet jenkins.slave <3>
```
<1> run puppet on all the dev nodes of your stack
<2> run on a subgroup of machines
<3> target a role

In a second step, you use icon:terminal[] `result` to retrieve from the database the result of your callfootnote:[polling is currently the sole supported workflow, server push notification could be implemented in the future].

### >_ result

You can view the result of a `runpuppet` by using the provided job id (`jid`)
```
→ cicd testing result -j 20160621104434055991
```
In case the result is not yet available the command will automatically be retry 12 times (3 min).

IMPORTANT: The pretty printer is tailored to work on jobid coming from `icon:terminal[] runpuppet`. For all other JIDs, you should add the `--raw` flag.

You can also ask for the last n executed commands:
```
→ cicd testing result -n 2
```

### >_ service

To know if a service is up and running, you would use:
```
→ cicd prod service status docker jenkins.slave
{
  "svappcavl736.prd.srv.cirb.lan": true
}
```
You can also restart a service. However such operation in only allowed for a single machine. Here is how to restart the `nexus` service :
```
→ cicd prod service restart nexus -n svappcavl761.prd.srv.cirb.lan
{
  "svappcavl761.prd.srv.cirb.lan": true
}
```

### >_ du

The command displays disk usage. Try:
```
→ cicd staging du -n svappcavl703.sta.srv.cirb.lan
```

### >_ setfacts

To set (or update) the four basic `facts` on a specific machine:
```
→ cicd dev setfacts -n fqdn --subgroup jenkins --role slave --zone dev --hostgroup bas
```

You can of course update just one fact with:
```
→ cicd dev setfacts -n fqdn --subgroup jenkins2
```
NOTE: the `setfacts` subcommand always requires a target node (`-n`)


### >_ state

Apply a configuration (called 'state' in Salt) on one machine.

```
→ cicd dev state CMD -n NODE
```

This command target one single node for safety reasons. If you wish to target multiple nodes, use the equivalent `pep` command within the console:

```
[cicd dev]$ pep -C "G@subgroup:puppet and G@hostgroup:cicd" state.apply puppet4-agent
```

### >_ orch

Salt is able to orchestrate deployment scenarios across machines.

The orchestration is executed on the salt master to allow inter minion requisites, like ordering the application of states on different minions that must not happen simultaneously, or for halting the state run on all minions if a minion fails one of its states (more about this topic can be found https://docs.saltstack.com/en/latest/topics/tutorials/states_pt5.html#orchestrate-runner[in the saltstack website]).

To write some specific orchestration scripts for your stack, you need to request a salt stack repository. For `bos` it would be named `salt-stack-bos`. This process is similar to the creation of `puppet-stack-bos` . The scripts should sit in the `orch` folder. You can find some examples http://stash.cirb.lan/projects/MIDDLEWARE/repos/salt-stack-middleware/browse/orch?at=refs%2Fheads%2Fmiddleware[here].

Orchestrate commands are executed with:

```
→ cicd testing orch CMD
```

### >_ foreman

Open a browser and display the relevant foreman page related to your query. For instance to get a list of all jenkins slaves and the link to its complete report, type:

```
cicd prod foreman jenkins.slave -s ci
```

### >_ console

For longer session within a specific zone, you can save some typing by opening a `console` for that zone. Inside the console, you would omit the zone from the command line. Here is an example:

```
→ cicd staging console

[cicd staging]$ facts
```

Another usage of the console is to run specific `salt` commands that are not exposed by the `cicd` command line. This is done via the #pep# shortcut. For instance:

[%autofit]
```
$ pep -G 'hostgroup:iam' file.replace '/etc/resolv.conf' pattern='192.168.34.250' repl='192.168.34.244' <1>

$ pep -L fqdn1,fqdn2 --client=local_async cicd.run_agent <2>
```
<1> #-G# means `grain` target (__grains__ is the salt terminology for facts).
<2> #-L# means `list` target +
#local_asyn# means the command is asynchronous and does not display its result (just a jid)

[TIP]
====
- Have a look at the saltstack documentation to learn more about https://docs.saltstack.com/en/latest/topics/targeting/#targeting-minions[targeting minions].
- Take a look https://docs.saltstack.com/en/latest/ref/index.html#salt-module-reference[here] for a list of possible commands.
====

### >_ help

The `help` subcommand will open the guide in a browser, display the list of available salt module and show the help for each of them.

```
→ cicd doc
Usage: cicd doc (html | modules | mod)
  Documentation utilities

Available options:
  -h,--help                Show this help text

Available commands:
  html                     Open the documentation in a browser
  modules                  Output all possible salt execution modules
  mod                      Doc about a specific salt module
```

### >_ pass

The `pass` subcommand is used to change the stored password. Handy whenever you change your AD password.

## Authentication
====
The permissions to target machines and perform actions are realized through our Active directory.
As an example to access the machines of the `irisbox` hostgroup, you will need to be part of the `GP_APP_SALT_IRISBOX` group.

These permissions should have been set for you already. If they don't, please contact the `cicd` team.
====

### AD password storage

The first time you use the `cicd-shell`, a prompt will ask you for your AD password.
This is required because every action realized is guarded by permission and recorded in database.

The prompt will propose you to store your password on the devbox.
Accept the proposition in order to avoid retyping your password for each subsequent actions.

Your password does not leave the devbox.
If you feel it might be in danger sitting in the devbox filesystem, you can add a level0 running script to remove the #.pwd# file when the devbox shutdowns.

## Install outside the devbox

Before installing the `cicd-shell` on any linux systemfootnote:[`macos` also works], you will need:

. the https://nixos.org/nix/[nix package manager] installed and active for your user.
. the https://github.com/CIRB/nixpkgs-config[cirb nixpkgs config]

You can then proceed to install with:

```
nix-env -f ~/.config/nixpkgs/pin.nix -i cicd-shell <1>
```
<1> the `-f` flag ensures that we point to the same nixpkgs version but can be omitted

TIP: You might want to place the configuration file in `~/.config/cicd/shell` instead of `/vagrant/config/shell`.

====
If you haven't installed `nix` already, here is the quick how to:

```
bash <(curl https://nixos.org/nix/install)
```
This will perform a single-user installation of Nix, meaning that /nix is owned by the invoking user. The script will only invoke `sudo` to create /nix if it doesn’t already exist. At that point, the script will prompt you for a password.

To activate `nix` in your shell, add the following line in your `.bash_profile`:

```
source ~/.nix-profile/etc/profile.d/nix.sh'
```
====
